### ISSUE TITLE
Define scope

### ISSUE THREAD

**Issue by torbencarstens** [tim-hat-die-hand-an-der-maus/architecture#1]

**Comment by BjoernPetersen** [comment]
### Requirements of the top of my head

- Add and remove movies from queue
  - Remove obviously needs permissions
- Mark movie as watched
- Prioritize queue
  - Voting system
  - Reorder by admin?
- View queue in different interfaces
  - Telegram
  - tim-hat-die-hand-an-der-maus.consulting

**Comment by torbencarstens** [comment]
- Create a poll on friday evening to choose the movie (x highest rated)
- auth for telegram and web
- mandatory movie rating after watching

**Comment by BjoernPetersen** [comment]
Scope restriction: The telegram bot only works in a pre-defined set of allowlisted chats which all access the same queue. The API does not know the concept of multiple groups/chats.

**Comment by torbencarstens** [comment]
pretty sure we're basically done with defining the (initial) scope since we've implemented all components and there are no outstanding feature requests (to my knowledge)
